name: SatProcessor
channels:
  - conda-forge
dependencies:
  - python=3.9
  - aiohttp=3.7.4
  - rasterio=1.2.4
  - pip
  - pip:
      - pystac=0.5.6
      - geojson=2.5.0
      - shapely=1.7.1.1
      - pytest=6.2.4
      - pytest-asyncio=0.15.1
